# Ce build permet de compiler le jeu avec Unity (job build)
# Et il lance un second job (sonar) pour l'analyse SonarCloud

name: Unity Build Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: Generate build version number
      id: version
      run: |
        VERSION="1.0.0.${{ github.run_number }}"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "::notice title=Build Version::$VERSION"
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Cache Unity Library
      uses: actions/cache@v3
      with:
        path: src/Library
        key: Library-${{ runner.os }}-${{ hashFiles('src/**/*.cs') }}
        restore-keys: |
          Library-${{ runner.os }}-
    - name: Build Unity project
      uses: game-ci/unity-builder@v4.3.0
      with:
        unityVersion: 6000.0.40f1
        targetPlatform: StandaloneWindows64
        projectPath: src  
        buildName: GaiasGuardian
        customParameters: -logFile /dev/stdout -debugCodeOptimization
      env:
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Build-${{ env.VERSION }}
        path: build/StandaloneWindows64/**
    - name: Set build summary
      run: |
        echo "### 🚀 Build version: \`${VERSION}\`" >> $GITHUB_STEP_SUMMARY
  sonar: # Librement inspiré du workflow suivant :  https://github.com/finol-digital/Card-Game-Simulator/blob/e2639469f86f09d186121d8ccaacefb9b69227e8/.github/workflows/main.yml#L157
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-6000.0.41f1-linux-il2cpp-3
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # important pour que SonarCloud ait accès à l’historique git complet
          lfs: true        
      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-lint-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: Library-lint-
      - name: Activate Unity
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        run: unity-editor -nographics -logFile /dev/stdout -quit -username "$UNITY_EMAIL" -password "$UNITY_PASSWORD" -serial "$UNITY_SERIAL"
      - name: Generate Solution
        run: unity-editor -nographics -logFile /dev/stdout -customBuildName jpp -projectPath src -executeMethod Packages.Rider.Editor.RiderScriptEditor.SyncSolution -quit
      - name: SonarQube Analysis
        env:
          FrameworkPathOverride: /opt/unity/Editor/Data/MonoBleedingEdge/
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd src
          sed -i '/<\/Project>/i\  <PropertyGroup>\n    <SonarQubeTestProject>false</SonarQubeTestProject>\n  </PropertyGroup>' Assembly-CSharp.csproj
          wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
          chmod +x ./dotnet-install.sh
          ./dotnet-install.sh --version latest
          apt-get update
          apt-get install -y openjdk-17-jre-headless
          apt-get install -y dotnet-sdk-6.0
          dotnet tool install dotnet-sonarscanner --tool-path .
          ./dotnet-sonarscanner begin \
            /o:"mrgautier256" \
            /k:"MrGautier256_Jeux-Video-Gaias-Guardian" \
            /d:sonar.token="$SONAR_TOKEN" \
            /d:sonar.exclusions=**/TextMesh*/**,**/Plugins/**,**/*.json,**/*.asmdef \
            /d:sonar.host.url=https://sonarcloud.io
          dotnet build src.sln
          ./dotnet-sonarscanner end /d:sonar.token="$SONAR_TOKEN"
          cd ..
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: src
          path: |
            src/**/*.sln
            src/**/*.csproj
            src/Assets/Scripts/**/*.cs