name: Unity Build Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: List files at root
      run: |
        pwd
        ls -la # Sur Linux

    - name: Cache Unity Library
      uses: actions/cache@v3
      with:
        path: src/Library
        key: Library-${{ runner.os }}-${{ hashFiles('src/**/*.cs') }}
        restore-keys: |
          Library-${{ runner.os }}-
    - name: Check system resources
      run: |
        free -h
        df -h
        ulimit -a

    - name: Debug scenes list
      run: |
        echo "Scenes in EditorBuildSettings:"
        cat src/ProjectSettings/EditorBuildSettings.asset | grep -A 1 path
        cd /home/runner/work/Jeux-Video-Gaias-Guardian/Jeux-Video-Gaias-Guardian/src

    - name: Build Unity project
      uses: game-ci/unity-builder@v4.3.0
      with:
        unityVersion: 6000.0.40f1
          # 2021.3.16f1
        targetPlatform: StandaloneWindows64
        projectPath: src     
        customParameters: -logFile /dev/stdout -debugCodeOptimization
      env:
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}

    - name: Upload Editor Log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: EditorLog
        path: /github/workspace/src/Editor.log

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Build
        path: src/build/**
